import pandas as pd

tablaSiembras = pd.read_csv('./Siembras.csv')
#print(tablaSiembras) 
#tablaMunicipios1=tablaSiembras[tablaSiembras["Ciudad"]=="Andes"].head(50)
#archivoHTML=tablaMunicipios1.to_html()
#archivoTEXTO=open("datosandes.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Barbosa"].head(50)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datosbarbosa.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Caldas"].head(50)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datoscaldas.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Támesis"].head(50)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datostamesis.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Támesis"].head(50)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datostamesis.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Yarumal"].head(50)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datosyarumal.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
# Datos medellin 
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Medellín"].head(50)
#tablaMunicipios2=tablaMunicipios2.sort_values(by="Arboles",ascending=False)
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("datosmedellin.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
# Datos Caucasia
#tablaMunicipios2=tablaSiembras[(tablaSiembras["Ciudad"]=="Caucasia") & (tablaSiembras["Hectareas"].head(50))]
#tablaMunicipios2=tablaSiembras[tablaSiembras["Ciudad"]=="Caucasia"]
#tablaMunicipios2=tablaMunicipios2["Hectareas"]
#archivoHTML=tablaMunicipios2.to_html()
#archivoTEXTO=open("tablacaucasia.html","w",encoding="utf-8")
#archivoTEXTO.write(archivoHTML)
#archivoTEXTO.close()
# Datos Santa fe de antioquia
tablaMunicipios2=tablaSiembras[(tablaSiembras["Ciudad"]=="Santa Fe de Antioquia") & (tablaSiembras["Arboles"]>250)]
tablaMunicipios2=tablaMunicipios2.sort_values(by="Hectareas",ascending=False)
archivoHTML=tablaMunicipios2.to_html()
archivoTEXTO=open("datossantafe.html","w",encoding="utf-8")
archivoTEXTO.write(archivoHTML)
archivoTEXTO.close()
